[package]
name = "otter-sim"
version = "0.1.0"
authors = ["Trevor McKay <trs.mckay@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"

[[bin]]
name = "otter-sim"
path = "src/main.rs"